export const LINE_BREAK = ["backspace", "]", "enter", "?"];
export const SPECIALKEYS = ["backspace", "tab", "capslock", "tab", "shift", "space", "enter"];

export const HOT_KEYS = [
  { name: "color", codes: [16, 18] },
  { name: "language", codes: [16, 17] }]

export const KEY_LAYOUTS = [
  { name: "1", ruName: "1", keyCode: 49 },
  { name: "2", ruName: "2", keyCode: 50 },
  { name: "3", ruName: "3", keyCode: 51 },
  { name: "4", ruName: "4", keyCode: 52 },
  { name: "5", ruName: "5", keyCode: 53 },
  { name: "6", ruName: "6", keyCode: 54 },
  { name: "7", ruName: "7", keyCode: 55 },
  { name: "8", ruName: "8", keyCode: 56 },
  { name: "9", ruName: "9", keyCode: 57 },
  { name: "0", ruName: "0", keyCode: 48 },
  { name: "backspace", ruName: "backspace", keyCode: 8 },
  { name: "tab", ruName: "tab", keyCode: 9 },
  { name: "q", ruName: "й", keyCode: 81 },
  { name: "w", ruName: "ц", keyCode: 87 },
  { name: "e", ruName: "у", keyCode: 69 },
  { name: "r", ruName: "к", keyCode: 82 },
  { name: "t", ruName: "е", keyCode: 84 },
  { name: "y", ruName: "н", keyCode: 89 },
  { name: "u", ruName: "г", keyCode: 85 },
  { name: "i", ruName: "ш", keyCode: 73 },
  { name: "o", ruName: "щ", keyCode: 79 },
  { name: "p", ruName: "з", keyCode: 80 },
  { name: "[", ruName: "х", keyCode: 219 },
  { name: "]", ruName: "ъ", keyCode: 221 },
  { name: "capslock", ruName: "capslock", keyCode: 20 },
  { name: "a", ruName: "ф", keyCode: 65 },
  { name: "s", ruName: "ы", keyCode: 83 },
  { name: "d", ruName: "в", keyCode: 68 },
  { name: "f", ruName: "а", keyCode: 70 },
  { name: "g", ruName: "п", keyCode: 71 },
  { name: "h", ruName: "р", keyCode: 72 },
  { name: "j", ruName: "о", keyCode: 74 },
  { name: "k", ruName: "л", keyCode: 75 },
  { name: "l", ruName: "д", keyCode: 76 },
  { name: ";", ruName: "э", keyCode: 222 },
  { name: "\\", ruName: "\\", keyCode: 220 },
  { name: "enter", ruName: "enter", keyCode: 13 },
  { name: "shift", ruName: "shift", keyCode: 16 },
  { name: "z", ruName: "я", keyCode: 90 },
  { name: "x", ruName: "ч", keyCode: 88 },
  { name: "c", ruName: "с", keyCode: 67 },
  { name: "v", ruName: "м", keyCode: 86 },
  { name: "b", ruName: "и", keyCode: 66 },
  { name: "n", ruName: "т", keyCode: 78 },
  { name: "m", ruName: "ь", keyCode: 77 },
  { name: ",", ruName: "б", keyCode: 188 },
  { name: ".", ruName: "ю", keyCode: 190 },
  { name: "?", ruName: ".", keyCode: 191 },
  { name: "ctrl", ruName: "ctrl", keyCode: 17 },
  { name: "alt", ruName: "alt", keyCode: 18 },
  { name: "space", ruName: "space", keyCode: 32 }
];